spring:
  datasource:
    url: jdbc:h2:mem:jwtdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: jwtbackend

server:
  port: 8080